### PR TITLE
chore:hide filter for not stuff user

### PR DESCRIPTION
**Pull request by im-awaism**
### PR fulfills these requirements
- [x] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [x] Tests for the changes have been added/updated (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [x] Product design
- [x] Backend (Database)
- [ ] Backend (API)
- [x] Frontend

### Describe the reason for change
We want to restrict basic user permissions so they can't access filters limited to staff members only.

#### What is the new behavior?
If the user is a stuff then only then he can access filters dropdown in Data Manager.

#### What is the current behavior?
All users have access to filters in Data Manager Page.

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### To Test.
User won't be able to see Filters by default. To see the filters in the Data Manager, you need to upgrade your user status to staff. Simply run the project to confirm the changes.

### CODE REVIEW

**Review by toobiza — CHANGES_REQUESTED** [review]
It looks good. I am about to approve it, I have two questions:

1. What is the motivation of have the dist folder? Shall it be in the .gitignore? I know it was there originally but just for my own understanding.
2. I do not see the scripts to make the users discussed in Slack staff members?

Other than that, it looks excellent!

**Comment by iam-dev0** [comment]
1.   By default, Django looks for a dist folder to serve the React frontend. This means that if you want to run Django without running the frontend project you can it will using just use the dist folder that is present. This setup allows you to run Django independently from the frontend, making development and deployment easier for the backend.

2.  I haven't written it yet.

**Comment by toobiza** [comment]
1. I see thanks for the explanation. I think the reason is related to your remark during the meeting that they are mixing django front end with react. If it was isolated then we would need it to have this workaround.
2. Let us have the scripts then merge it then.

**Comment by iam-dev0** [comment]
Will write the script today. Thanks

**Review by toobiza — APPROVED** [review]
I will approve it, please merge it once you have the scrips and deploy it directly.
Thanks @im-awaism

**Review by toobiza — APPROVED** [review]
It looks great!

**Pull request merged**
